### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by otidev** [otidev/moonengine#2]
**NOTE**: it would be greatly appreciated if you'd help with these!

- [ ] Docs
- [x] CMake support
- [x] Examples
- [ ] More detailed/better collision code
- [ ] Code of Conduct
- [ ] Better camera system (like the one used for the rendertargets)
- [ ] Take away `fg` and `bg` limitations in `Map`

**Comment by batunpc** [comment]
Hello @otidev I am participating [Hacktoberfest](https://hacktoberfest.com/) I would like to investigate this issue. Particularly for CMake support
